/**:
  ros__parameters:

    # For beginners, we downscale velocity and acceleration limits.
    default_velocity_scaling_factor: 1.0
    default_acceleration_scaling_factor: 1.0

    joint_limits:
      joint_1:
        has_velocity_limits: true
        max_velocity: 3.67
        has_acceleration_limits: true
        max_acceleration: 0.734
        min_position: -3.14
        max_position: 3.14

      joint_2:
        has_velocity_limits: true
        max_velocity: 3.32
        has_acceleration_limits: true
        max_acceleration: 0.664
        min_position: -1.3
        max_position: 1.3

      joint_3:
        has_velocity_limits: true
        max_velocity: 3.67
        has_acceleration_limits: true
        max_acceleration: 0.734
        min_position: -2.0
        max_position: 2.0

      joint_4:
        has_velocity_limits: true
        max_velocity: 6.98
        has_acceleration_limits: true
        max_acceleration: 1.396
        min_position: -3.14
        max_position: 3.14

      joint_5:
        has_velocity_limits: true
        max_velocity: 6.98
        has_acceleration_limits: true
        max_acceleration: 1.396
        min_position: -2.0
        max_position: 2.0

      joint_6:
        has_velocity_limits: true
        max_velocity: 10.47
        has_acceleration_limits: true
        max_acceleration: 2.094
        min_position: -3.14
        max_position: 3.14

